default: fetch

UNAME?=$(shell uname)

ifeq ($(UNAME),Darwin)
	LIBEXT=dylib
else
	LIBEXT=so
endif

all:
	make -C $(WORKDIR) $@

clean:
	-rm -fr $(WORKDIR)

distclean:
	-rm -fr $(TARBALL)

.PHONY: fetch
fetch: $(TARBALL)
$(TARBALL):
	fetch.sh -o $@ "$(URL)"

$(PREFIX)/lib $(PREFIX)/include:
	mkdir $@

workdir: $(WORKDIR)
$(WORKDIR): $(TARBALL)
	tar $(TARFLAGS) -xf $<

configure-autoconf: $(WORKDIR)/Makefile
$(WORKDIR)/Makefile: | $(WORKDIR)
	cd $(WORKDIR); ./configure --prefix=$(PREFIX)
